
FROM mcr.microsoft.com/devcontainers/typescript-node:20

ARG USERNAME=node
ARG USER_UID=1000
ARG USER_GID=1000

RUN apt-get update 
RUN apt-get install -y sudo 
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME 
RUN chmod 0440 /etc/sudoers.d/$USERNAME 
RUN echo "umask 0002" >> /home/$USERNAME/.bashrc
